## Argo CD configuration
## Ref: https://github.com/argoproj/argo-cd

## Argo Configs
configs:
  params:
    server.insecure: true
    create: true

  repositories: 
    ## Self-hosted Git repository for in gitea, used for argo app manifests
    ## <service-name>.<namespace-name>.svc.cluster.local
    gitops-repo:
      url: "http://host.docker.internal:3000/gitea_admin/platform-ops"