{{- range .Values.services }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}-deployment
  namespace: {{ .namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .name }}
  template:
    metadata:
      labels:
        app: {{ .name }}
    spec:
      containers:
        - name: {{ .name }}
          image: {{ .image }}
          ports:
            - containerPort: {{ .port }}
          envFrom:
            - configMapRef:
                name: {{ .name }}-config
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}-service
  namespace: {{ .namespace }}
spec:
  selector:
    app: {{ .name }}
  ports:
    - protocol: TCP
      port: {{ .port }}
      targetPort: {{ .port }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .name }}-config
  namespace: {{ .namespace }}
data:
  {{ range $key, $value := .config }}
  {{ $key }}: "{{ $value }}"
  {{- end }}
{{- end }}