{{- range .Values.applications }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .name }}
spec:
  project: {{ .project }}
  source:
    chart: {{ .chart }}
    repoURL: {{ .repoURL }} 
    targetRevision: {{ .targetRevision }}
  destination:
    name: "in-cluster"
    namespace: {{ .namespace }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .namespace }}
{{- end }}