apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: platform-apps-route
  namespace: {{ .Values.namespace }}
spec:
  parentRefs:
    - name: gateway
      namespace: gateway
  hostnames:
    - {{ .Values.hostname }}
  rules:
    {{- range .Values.services }}
    - matches:
        - path:
            type: PathPrefix
            value: /{{ .name }}
      # filters:
      #   - type: URLRewrite
      #     urlRewrite:
      #       path:
      #         type: ReplacePrefixMatch
      #         replacePrefixMatch: /
              
      backendRefs:
        - name: {{ .name }}-service
          port: {{ .port }}
    {{- end }}
---
